# Generated by Django 2.2 on 2021-02-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icecream', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ice_cream',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
