# Generated by Django 2.2 on 2021-02-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icecream', '0002_auto_20210219_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ice_cream',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
