# Generated by Django 2.2.19 on 2021-04-21 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('icecream', '0003_auto_20210224_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ice_cream',
            name='name',
            field=models.CharField(help_text='Название мороженного', max_length=40, verbose_name='имя'),
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favourite_icecream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_icecream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_favourite', to='icecream.Ice_cream')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icecream_favourite', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
