# Generated by Django 2.2.19 on 2021-04-24 15:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('icecream', '0004_auto_20210421_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='ice_cream',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
